title: Your Name
logo: /assets/img/headshot_circle.png
description: Professional CV and portfolio site.
show_downloads: true
baseurl: ""
url: "https://mufauzan.github.io"
markdown: kramdown
theme: jekyll-theme-minimal
